name: CI-xClass

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 1.8
                uses: actions/setup-java@v1
                with:
                    java-version: 1.8
            #            -   name: Build with Maven
            #                run:  mvn -B package --file pom.xml
            #            -   name: check
            #                run:  ls -al /home/runner/work/xClass/xClass/target/xclass-0.0.1-SNAPSHOT.jar
            -   name: test
                env:
                    privateKey: ${{secrets.PRIVATEKEY}}
                    knownHosts: ${{secrets.KNOWNHOSTS}}
                    host:       ${{secrets.HOST}}
                    user:       ${{secrets.USER}}
                    temp:       ${{secrets.TEMP}}
                run:  |
                      mkdir -p ~/.ssh/
                      echo "$privateKey" > ~/.ssh/private.key
                      chmod 600 ~/.ssh/private.key
                      echo "$knownHosts" > ~/.ssh/known_hosts
                      ls -al ~/.ssh/
                      ping $host -c 9
                      ssh -p 50022 -i ~/.ssh/private.key root@xclass.highspeed.vip hostname














#                      echo "ssh-keygen"
#                      ssh-keygen -y -e -f ~/.ssh/private.key
#                      echo "ssh-keyscan"
#                      ssh-keyscan 140.238.155.2
#                          echo ${{secrets.KNOWNHOSTS}} > ~/.ssh/known_hosts

#                                        echo ${{secrets.PRIVATEKEY}} > ~/.ssh/private.key
#    ssh -i ./ycz.log -p 50022 -o "StrictHostKeyChecking no" root@xclass.highspeed.vip hostname
#    scp -P 50022 -i ./ycz.log -o "StrictHostKeyChecking no" ./ycz.log root@xclass.highspeed.vip:/tmp
